import { useEffect, useMemo, useRef, useState } from 'react';
import { api, type FrontlineReport, type FrontlineStatus } from '../lib/api';
import { useAuth } from '../lib/auth';

export default function FrontlinePage() {
  const { user } = useAuth();
  const isAdmin = user?.roleName === 'Admin';
  const [report, setReport] = useState<FrontlineReport | null>(null);
  const [status, setStatus] = useState<FrontlineStatus | null>(null);
  const [syncing, setSyncing] = useState(false);
  const [loadingReport, setLoadingReport] = useState(false);
  const [page, setPage] = useState(1);
  const pageSize = 50;
  const filterAreaRef = useRef<HTMLElement>(null);
  const formatDate = (value: string | null | undefined) => {
    if (!value) return '—';
    const raw = String(value).trim();
    const parsed = new Date(/^\d{4}-\d{2}-\d{2}$/.test(raw) ? `${raw}T00:00:00Z` : raw);
    return Number.isNaN(parsed.getTime()) ? '—' : new Intl.DateTimeFormat('en-US', { month: '2-digit', day: '2-digit', year: 'numeric', timeZone: 'UTC' }).format(parsed);
  };
  const formatSyncTime = (value: string | null) => value ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric', hour: 'numeric', minute: '2-digit', second: '2-digit', hour12: true, timeZone: 'Asia/Manila' }).format(parseBackendTimestamp(value)) : 'never';
  const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [cso, setCso] = useState<string[]>([]); const [type, setType] = useState<string[]>([]); const [division, setDivision] = useState<string[]>([]); const [openFilter, setOpenFilter] = useState<string | null>(null); const [message, setMessage] = useState('');
  const load = async (filters = { start, end, cso, type, division }) => { setLoadingReport(true); try { const [nextStatus, nextReport] = await Promise.all([api.frontline.status(), api.frontline.report(filters)]); setStatus(nextStatus); setReport(nextReport); setPage(1); } catch (error) { setMessage((error as Error).message); } finally { setLoadingReport(false); } };
  const syncNow = async () => { setSyncing(true); setMessage(''); try { await api.admin.syncFrontline(); await load(); } catch (error) { setMessage((error as Error).message); } finally { setSyncing(false); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (!openFilter) return; const close = (event: MouseEvent) => { if (!filterAreaRef.current?.contains(event.target as Node)) setOpenFilter(null); }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, [openFilter]);
  const options = useMemo(() => ({ csos: report?.csos || [], types: report?.types || [], divisions: report?.divisions || [] }), [report]);
  const hasFilters = Boolean(start || end || cso.length || type.length || division.length);
  const pageCount = report ? Math.max(1, Math.ceil(report.records.length / pageSize)) : 1;
  const pageRecords = report?.records.slice((page - 1) * pageSize, page * pageSize) || [];
  return <div className="min-h-[calc(100vh-128px)] bg-[#f4f3f6]">
    <div className="mb-7"><h1 className="text-[28px] font-semibold tracking-tight text-[#1d1d1f]">Frontline Monitor</h1><p className="mt-1.5 text-[14px] text-[#3c3c43]">Podium only · CSO frontline activity and service trends.</p><div className="mt-3"><p className={`text-[13px] font-medium ${status?.connected ? 'text-[#248a3d]' : 'text-[#1d1d1f]'}`}>{status?.connected ? `● Connected · ${status.sourceName || 'Google Sheets'}` : '● Google Sheets not connected'}</p><p className="mt-1 text-[12px] text-[#3c3c43]">{status?.connected ? <>Read-only access · Last synced {formatSyncTime(status.lastSyncedAt)}{isAdmin && <>{' · '}<button aria-label={syncing ? 'Refreshing data' : 'Refresh data'} onClick={() => void syncNow()} disabled={syncing || loadingReport} className="inline-flex items-center gap-1 font-medium text-[#2563eb] hover:underline disabled:opacity-50">{syncing ? <Spinner /> : 'Click Refresh data to check for updates'}</button></>}</> : 'Ask an Admin to configure the Google Sheets source.'}</p></div></div>
    <section ref={filterAreaRef} className="mb-5 rounded-2xl border border-[#e5e5e7] bg-white p-4"><div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-5"><input type="date" value={start} onChange={(event) => setStart(event.target.value)} className="h-9 rounded-lg border border-[#d2d2d7] px-2 text-[12px]" /><input type="date" value={end} onChange={(event) => setEnd(event.target.value)} className="h-9 rounded-lg border border-[#d2d2d7] px-2 text-[12px]" /><MultiSelect label="All CSOs" options={options.csos} selected={cso} onChange={setCso} open={openFilter === 'cso'} onOpen={() => setOpenFilter(openFilter === 'cso' ? null : 'cso')} /><MultiSelect label="All transaction types" options={options.types} selected={type} onChange={setType} open={openFilter === 'type'} onOpen={() => setOpenFilter(openFilter === 'type' ? null : 'type')} /><MultiSelect label="All divisions" options={options.divisions} selected={division} onChange={setDivision} open={openFilter === 'division'} onOpen={() => setOpenFilter(openFilter === 'division' ? null : 'division')} /></div><div className="mt-3 flex flex-wrap gap-2"><button aria-label={loadingReport ? 'Applying filters' : 'Apply filters'} onClick={() => { setOpenFilter(null); void load(); }} disabled={loadingReport || syncing} className="inline-flex h-[34px] min-w-[104px] items-center justify-center gap-2 rounded-full bg-[#1d1d1f] px-4 py-2 text-[12px] font-semibold text-white disabled:opacity-40">{loadingReport ? <Spinner /> : 'Apply filters'}</button>{hasFilters && <button type="button" onClick={() => { setStart(''); setEnd(''); setCso([]); setType([]); setDivision([]); setOpenFilter(null); void load({ start: '', end: '', cso: [], type: [], division: [] }); }} disabled={loadingReport || syncing} className="inline-flex h-[34px] items-center justify-center rounded-full border border-[#d2d2d7] px-4 py-2 text-[12px] font-medium text-[#3c3c43] disabled:opacity-40">Reset filters</button>}</div></section>
    {message && <p className="mb-4 text-[13px] text-[#b91c1c]">{message}</p>}
    {report && <><div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><Metric label="Total assists" value={report.total.toLocaleString()} /><Metric label="Average AHT" value={`${report.averageAht.toFixed(1)} min`} /><Metric label="CSOs represented" value={report.csos.length.toLocaleString()} /></div><div className="mt-5 grid grid-cols-1 gap-4 lg:grid-cols-3"><Breakdown title="By CSO" items={report.csos} /><Breakdown title="By transaction" items={report.types} /><Breakdown title="By division" items={report.divisions} /></div><div className="mt-5 overflow-hidden rounded-2xl border border-[#e5e5e7] bg-white"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-[#e5e5e7] px-4 py-3"><div className="text-[13px] font-semibold text-[#1d1d1f]">Recent records</div><span className="text-[12px] text-[#6e6e73]">{report.records.length ? `${(page - 1) * pageSize + 1}–${Math.min(page * pageSize, report.records.length)} of ${report.records.length}` : '0 records'}</span></div><div className="overflow-x-auto"><table className="w-full text-left text-[12px]"><thead className="bg-[#fafafa] text-[10px] uppercase tracking-wider text-[#6e6e73]"><tr><th className="px-4 py-2">Date</th><th className="px-4 py-2">CSO</th><th className="px-4 py-2">Type</th><th className="px-4 py-2">Division</th><th className="px-4 py-2">AHT</th><th className="px-4 py-2">Issue</th><th className="px-4 py-2">Source</th></tr></thead><tbody>{pageRecords.map((row) => <tr key={row.id} className="border-t border-[#f0f0f2]"><td className="whitespace-nowrap px-4 py-2.5 text-[#3c3c43]">{formatDate(row.occurred_date)}</td><td className="px-4 py-2.5 font-medium text-[#3c3c43]">{row.cso || '—'}</td><td className="px-4 py-2.5 text-[#3c3c43]">{row.transaction_type || '—'}</td><td className="px-4 py-2.5 text-[#3c3c43]">{row.product_division || '—'}</td><td className="px-4 py-2.5 text-[#3c3c43]">{row.aht_minutes == null ? '—' : `${Number(row.aht_minutes).toFixed(1)} min`}</td><td className="max-w-[22rem] truncate px-4 py-2.5 text-[#3c3c43]">{row.issue || '—'}</td><td className="whitespace-nowrap px-4 py-2.5 text-[#6e6e73]">{row.source_sheet} · row {row.source_row}</td></tr>)}</tbody></table></div><div className="sticky bottom-0 flex items-center justify-end gap-2 border-t border-[#e5e5e7] bg-white px-4 py-3">{pageCount > 1 && <><button type="button" onClick={() => setPage((current) => Math.max(1, current - 1))} disabled={page === 1} className="rounded-full border border-[#d2d2d7] px-3 py-1.5 text-[12px] text-[#3c3c43] disabled:opacity-40">Previous</button><span className="min-w-[72px] text-center text-[12px] text-[#3c3c43]">Page {page} of {pageCount}</span><button type="button" onClick={() => setPage((current) => Math.min(pageCount, current + 1))} disabled={page >= pageCount} className="rounded-full border border-[#d2d2d7] px-3 py-1.5 text-[12px] text-[#3c3c43] disabled:opacity-40">Next</button></>}</div></div></>}
  </div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-[#e5e5e7] bg-white p-4"><p className="text-[11px] uppercase tracking-wider text-[#6e6e73]">{label}</p><p className="mt-2 text-[24px] font-semibold tracking-tight text-[#1d1d1f]">{value}</p></div>; }
function Breakdown({ title, items }: { title: string; items: Array<[string, number]> }) { const total = items.reduce((sum, [, count]) => sum + count, 0); return <div className="rounded-2xl border border-[#e5e5e7] bg-white p-4"><h2 className="text-[13px] font-semibold text-[#1d1d1f]">{title}</h2><div className="mt-3 space-y-2">{items.slice(0, 6).map(([name, count]) => <div key={name} className="flex items-center gap-3 text-[12px]"><span className="min-w-0 flex-1 truncate text-[#3c3c43]">{name}</span><span className="font-medium text-[#1d1d1f]">{count}</span><span className="h-1.5 w-16 overflow-hidden rounded-full bg-[#f0f0f2]"><span className="block h-full rounded-full bg-[#8b8b93]" style={{ width: `${total ? Math.max(4, count / total * 100) : 0}%` }} /></span></div>)}</div></div>; }
function Spinner() { return <span className="h-3 w-3 animate-spin rounded-full border-2 border-current/30 border-t-current" aria-hidden="true" />; }

function parseBackendTimestamp(value: string) {
  return new Date(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(value) ? `${value.replace(' ', 'T')}Z` : value);
}

function MultiSelect({ label, options, selected, onChange, open, onOpen }: { label: string; options: Array<[string, number]>; selected: string[]; onChange: (values: string[]) => void; open: boolean; onOpen: () => void }) {
  return <div className="relative min-w-0"><button type="button" aria-expanded={open} onClick={onOpen} className="flex h-9 w-full items-center justify-between gap-2 rounded-lg border border-[#d2d2d7] bg-white px-2 text-left text-[12px] text-[#3c3c43]"><span className="min-w-0 truncate">{selected.length ? `${selected.length} selected` : label}</span><span className="text-[10px] text-[#6e6e73]">⌄</span></button>{open && <div className="absolute left-0 right-0 z-10 mt-1 max-h-64 overflow-auto rounded-lg border border-[#d2d2d7] bg-white p-1 shadow-[0_8px_24px_rgba(0,0,0,0.08)]">{options.length ? options.map(([name, count]) => <label key={name} className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-[12px] text-[#3c3c43] hover:bg-[#f5f5f7]"><input type="checkbox" checked={selected.includes(name)} onChange={(event) => onChange(event.target.checked ? [...selected, name] : selected.filter((value) => value !== name))} /><span className="min-w-0 flex-1 truncate">{name}</span><span className="text-[11px] text-[#6e6e73]">{count}</span></label>) : <p className="px-2 py-2 text-[12px] text-[#6e6e73]">No options</p>}</div>}</div>;
}
