import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api, type EndorsementEngineer } from '../../lib/api';

export default function AdminEngineersPage() {
  const [engineers, setEngineers] = useState<EndorsementEngineer[]>([]);
  const [editing, setEditing] = useState<{ id: number; name: string } | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [newName, setNewName] = useState('');

  const load = async () => { const result = await api.endorsements.roster(); setEngineers(result.roster); };
  useEffect(() => { void load().catch((error) => setMessage((error as Error).message)); }, []);
  const save = async () => { if (!editing?.name.trim()) return; setBusy(true); setMessage(''); try { await api.endorsements.updateRosterEngineer(editing.id, editing.name.trim()); setEditing(null); setMessage('Engineer name updated.'); await load(); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } };
  const remove = async (engineer: EndorsementEngineer) => { if (!window.confirm(`Remove ${engineer.full_name} from the Engineer roster? Existing endorsements will be preserved.`)) return; setBusy(true); setMessage(''); try { await api.endorsements.deleteRosterEngineer(engineer.id); setMessage('Engineer removed from the roster.'); await load(); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } };
  const add = async () => { const name = newName.trim(); if (!name) return; setBusy(true); setMessage(''); try { await api.endorsements.addRosterEngineer(name); setNewName(''); setMessage('Engineer added to the roster.'); await load(); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } };

  return <div className="space-y-8">
    <div><Link to="/admin" className="mb-2 inline-flex text-[12px] font-medium text-[#6e6e73] hover:text-[#1d1d1f]">← Back to Manage</Link><h1 className="text-[26px] font-semibold tracking-tight text-[#1d1d1f]">Engineers</h1><p className="mt-1 text-[14px] text-[#6e6e73]">Manage Engineer names used by Engineer Endorsements. Daily availability is managed separately.</p></div>
    {message && <div role="status" className="flex items-center justify-between gap-3 border border-[#e5e5e7] bg-white px-4 py-3 text-[13px] text-[#3c3c43]"><span>{message}</span><button type="button" onClick={() => setMessage('')} aria-label="Dismiss message">×</button></div>}
    <section className="rounded-2xl border border-[#e5e5e7] bg-white p-5"><div className="mb-4"><h2 className="text-[15px] font-semibold text-[#1d1d1f]">Engineer roster</h2><p className="mt-1 text-[12px] text-[#6e6e73]">Add, rename, or remove Engineer names. Daily availability is managed separately.</p></div><form className="mb-5 flex max-w-md gap-2" onSubmit={(event) => { event.preventDefault(); void add(); }}><input value={newName} onChange={(event) => setNewName(event.target.value)} placeholder="Engineer name" aria-label="Engineer name" className="h-9 min-w-0 flex-1 rounded-lg border border-[#d2d2d7] px-3 text-[12px]" /><button type="submit" disabled={busy || !newName.trim()} className="rounded-full bg-[#1d1d1f] px-4 py-2 text-[11px] font-semibold text-white disabled:opacity-40">Add Engineer</button></form><div className="space-y-2">{engineers.length ? engineers.map((engineer) => editing?.id === engineer.id ? <div key={engineer.id} className="flex flex-wrap gap-2 rounded-xl border border-[#e5e5e7] p-3"><input autoFocus value={editing.name} onChange={(event) => setEditing({ ...editing, name: event.target.value })} onKeyDown={(event) => { if (event.key === 'Enter') void save(); if (event.key === 'Escape') setEditing(null); }} aria-label="Engineer name" className="h-9 min-w-0 flex-1 rounded-lg border border-[#d2d2d7] px-3 text-[12px]" /><button type="button" onClick={() => void save()} disabled={busy || !editing.name.trim()} className="rounded-full bg-[#1d1d1f] px-3 py-2 text-[11px] font-semibold text-white disabled:opacity-40">Save</button><button type="button" onClick={() => setEditing(null)} className="rounded-full border border-[#d2d2d7] px-3 py-2 text-[11px]">Cancel</button></div> : <div key={engineer.id} className="flex items-center gap-3 rounded-xl border border-[#e5e5e7] bg-[#fafafa] px-3 py-3"><span className="min-w-0 flex-1 text-[13px] font-medium text-[#3c3c43]">{engineer.full_name}</span><button type="button" onClick={() => setEditing({ id: engineer.id, name: engineer.full_name })} disabled={busy} className="text-[11px] font-medium text-[#3c3c43] underline disabled:opacity-40">Edit name</button><button type="button" onClick={() => void remove(engineer)} disabled={busy} className="text-[11px] font-medium text-[#6e6e73] underline disabled:opacity-40">Delete</button></div>) : <p className="text-[12px] text-[#6e6e73]">No Engineers in the roster.</p>}</div></section>
  </div>;
}
