import { useState } from 'react';
import { Link } from 'react-router-dom';
import { api, type StorageEmployee } from '../../lib/api';
import { invalidateQuery, useCachedQuery } from '../../lib/queryCache';

export default function AdminStorageLocatorPage() {
  const query = useCachedQuery<StorageEmployee[]>('storage-employees', api.admin.getStorageEmployees);
  const employees = query.data || [];
  const [number, setNumber] = useState(''); const [name, setName] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const add = async () => { if (!number.trim() || !name.trim()) return; setBusy(true); setError(''); try { await api.admin.addStorageEmployee(number, name); setNumber(''); setName(''); invalidateQuery('storage-employees'); await query.refresh(); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } };
  const toggle = async (employee: StorageEmployee) => { try { await api.admin.updateStorageEmployee(employee.id, { employeeNumber: employee.employeeNumber, fullName: employee.fullName, active: !Boolean(employee.active) }); invalidateQuery('storage-employees'); await query.refresh(); } catch (err) { setError((err as Error).message); } };
  return <div className="space-y-8"><div><Link to="/admin" className="text-[12px] text-[#6e6e73] hover:text-[#1d1d1f]">← Back to Admin</Link><h1 className="mt-3 text-[28px] font-semibold tracking-tight text-[#1d1d1f]">Storage Locator</h1><p className="mt-1 text-[14px] text-[#6e6e73]">Manage employee numbers used to verify IN and OUT operations.</p></div><section className="rounded-2xl border border-[#e5e5e7] bg-white p-5"><h2 className="text-[14px] font-semibold text-[#1d1d1f]">Add employee</h2><div className="mt-4 grid gap-2 sm:grid-cols-[180px_1fr_auto]"><input value={number} onChange={(e) => setNumber(e.target.value)} placeholder="Employee number" className="h-10 rounded-xl border border-[#d2d2d7] px-3 text-[12px]" /><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Full name" onKeyDown={(e) => e.key === 'Enter' && void add()} className="h-10 rounded-xl border border-[#d2d2d7] px-3 text-[12px]" /><button type="button" onClick={() => void add()} disabled={busy || !number.trim() || !name.trim()} className="rounded-xl bg-[#1d1d1f] px-5 py-2 text-[12px] font-semibold text-white disabled:opacity-40">{busy ? 'Adding…' : 'Add employee'}</button></div>{error && <p className="mt-3 text-[12px] text-[#a33a3a]">{error}</p>}</section><section className="overflow-hidden rounded-2xl border border-[#e5e5e7] bg-white"><div className="border-b border-[#e5e5e7] px-5 py-4"><h2 className="text-[14px] font-semibold text-[#1d1d1f]">Verified employees · {employees.length}</h2></div>{query.loading ? <p className="p-5 text-[12px] text-[#6e6e73]">Loading employees…</p> : <div className="divide-y divide-[#f0f0f2]">{employees.map((employee) => <div key={employee.id} className="flex items-center justify-between gap-3 px-5 py-4"><div><p className="text-[13px] font-semibold text-[#1d1d1f]">{employee.fullName}</p><p className="mt-1 text-[11px] text-[#6e6e73]">{employee.employeeNumber}</p></div><button type="button" onClick={() => void toggle(employee)} className={`rounded-full border px-3 py-1.5 text-[11px] font-semibold ${employee.active ? 'border-[#cfe8d6] text-[#27633a]' : 'border-[#d2d2d7] text-[#86868b]'}`}>{employee.active ? 'Active' : 'Inactive'}</button></div>)}{!employees.length && <p className="p-5 text-[12px] text-[#6e6e73]">No verified employees yet.</p>}</div>}</section></div>;
}
